version: "3.4"

services:

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14250:14250"

  # OTel Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: "--config=/etc/otel-collector-config.yaml ${OTELCOL_ARGS}"
    # Change the "source" path below to swap out collector config files!
    volumes:
      - type: bind
        source: ./otel-collector-config.yaml
        target: /etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55670:55679" # zpages extension
      - "55681:55681" # http
    environment:
      # uses .env file
      X_API_KEY: "$X_API_KEY"
    depends_on:
      - jaeger
  
  # Spring Petclinic using OTel Instrumentation JAR
  otel-java-basic:
    image: kjtully/otel-java-basic:latest
    container_name: otel-java-basic
    ports:
      - "8080:8080"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=otel-java-basic,service.namespace=kjt-otel-test"
    depends_on:
      - otel-collector
  
  # Spring Petclinic using AppD Instrumentation JAR
  appd-java-basic:
    image: kjtully/appd-java-basic:latest
    container_name: appd-java-basic
    ports:
      - "8081:8080"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=appd-java-basic,service.namespace=kjt-otel-test"
      APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}"
      APPDYNAMICS_AGENT_ACCOUNT_NAME: "${APPDYNAMICS_AGENT_ACCOUNT_NAME}"
      APPDYNAMICS_CONTROLLER_HOST_NAME: "${APPDYNAMICS_CONTROLLER_HOST_NAME}"
      APPDYNAMICS_CONTROLLER_PORT: "${APPDYNAMICS_CONTROLLER_PORT}"
      APPDYNAMICS_CONTROLLER_SSL_ENABLED: "${APPDYNAMICS_CONTROLLER_SSL_ENABLED}"
      APPDYNAMICS_AGENT_APPLICATION_NAME: "${APPDYNAMICS_AGENT_APPLICATION_NAME}"
      APPDYNAMICS_AGENT_TIER_NAME: "appd-java-basic"
      APPDYNAMICS_AGENT_NODE_NAME: "reuse"
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME: "true"
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX: "appd-java-basic-node"
    depends_on:
      - otel-collector
